version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres} # Change this password
      POSTGRES_DB: ${POSTGRES_DB:-postgres} 
      # Uncomment to change the default location of the database files
      # PGDATA: /var/lib/postgresql/data/db-files/
      # If you set POSTGRES_HOST_AUTH_METHOD to trust, then POSTGRES_PASSWORD is not required.
      # POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD:-trust}       
    volumes:
       - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    # Always restart the container if it stops, except that when the container is stopped (manually or otherwise)
    #restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin} # Change this password
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    # Always restart the container if it stops, except that when the container is stopped (manually or otherwise)
    #restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    pgdata:
    pgadmin: